### ISSUE TITLE
Link Injector

### ISSUE THREAD

**Issue by nadar** [dev7ch/vertico#1]
You should use the link injector instead of copy pasting the following code between all your projects. DRY

https://github.com/dev7ch/vertico/blob/master/blocks/BoxBlock.php#L66

**Comment by dev7ch** [comment]
Yes you are right, there is a more smart way to add links. 

I decided to use the 'good old style' because if you create a link field via `./vendor/bin/luya cms/block/create` the `linkInjectors() ` function is unfortunally not used.

So image if you would be new in LUYA, i think it´s better to see more consistency but to highlight the ` linkInjectors() ` i ´ve added an introduction for LUYA deep divers ;)

https://github.com/dev7ch/vertico/blob/master/blocks/BoxBlock.php#L66

**Comment by nadar** [comment]
@dev7ch well, i do not agree with you in this case, as your array construction with if/else is rather more complex then just using the linkinjector!

**Comment by dev7ch** [comment]
yes, sure it´s more complex, but please imagine if you were new to LUYA ...

On top of that its gives you an idea how Yii is working in the backend.

Hope you can understand and be happy that the use of linkInjectors() is explained

**Comment by nadar** [comment]
But if its more complex it makes no sense to use such code, when there is a very smart solution. Its not even Yii related source code, its just `if else` with values where you have no idea what they stand for `$linkData['type'] == '1'`. 

```php
$linkData = $this->getVarValue('link', null);
        $data = null;
        if ($linkData) {
            if ($linkData['type'] == '1') {
                $menu = Yii::$app->menu->find()->where(['nav_id' => $linkData['value']])->one();
                if ($menu) {
                    $data = $menu->getLink();
                }
            }
            if ($linkData['type'] == '2') {
                $data = $linkData['value'];
            }
        }
        return $data;
```

**Comment by dev7ch** [comment]
very smart would be if the link field would be generated correctly by the console commands

**Comment by dev7ch** [comment]
the smart solution is explained ... i ll use your input for the next project, thx

**Comment by nadar** [comment]
> very smart would be if the link field would be generated correctly by the console commands

Make an issue, so i will implement this feature. Which means you can now already switch to the link injector ;-)
