### ISSUE TITLE
Readme SQL & General Feedback

### ISSUE THREAD

**Issue by nadar** [dev7ch/vertico#2]
In the readme you talk about sql files

+ where are they located?
+ what is the reason for them? Does it not make more sense to understand the `migrate` and `admin/setup` command instead. Maybe people don't even use mysql.

Anyhow, i like the template a lot! You should change the composer.json to match your package name, make a release and publish on packagist. So we could share this project from the luyadev twitter account.

**Comment by dev7ch** [comment]
Thanks for your feedback.

- [Package on Packagist](https://packagist.org/packages/dev7ch/vertico) is created
- A demo database is loclated in the configs/ folder

A demo database is needed to give people who are new on LUYA a result after the installation as it is shown on the screenshot, futher it shows the integration of cmslayouts.

As you can see in the the readme file its optionally to use the demo database
